# Generated by Django 4.0.2 on 2022-02-04 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
