# Generated by Django 4.0.2 on 2022-02-04 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='title',
            new_name='name',
        ),
    ]
